--add unique index
CREATE UNIQUE INDEX UNIQUE_INDEX ON [TABLENAME] (COLS) WITH IGNORE_DUP_KEY ON [PRIMARY];

--dedupe
SELECT TOP 0 * INTO NEW_TABLE FROM OLD_TABLE;
CREATE UNIQUE INDEX UNIQUE_INDEX ON NEW_TABLE (COLS) WITH IGNORE_DUP_KEY ON [PRIMARY];
SELECT TOP 0 * INTO NEW_TABLE FROM OLD_TABLE;
DROP TABLE OLD_TABLE;
SP_RENAME NEW_TABLE, OLD_TABLE;

--add unique id
ALTER TABLE [TABLENAME] ADD [UNIQUE_ID] BIGINT IDENTITY;

--CONVERT COL TO VARCHAR
ALTER TABLE [TABLENAME] ADD [TEMP_COLUMN] VARCHAR(255);
UPDATE [TABLENAME] SET [TEMP_COLUMN] = CAST([COLUMNNAME] AS VARCHAR(255));
ALTER TABLE [TABLENAME] DROP COLUMN [COLUMNNAME];
ALTER TABLE [TABLENAME] ADD [COLUMNNAME] VARCHAR(255);
UPDATE [TABLENAME] SET [COLUMNNAME] = [TEMP_COLUMN];
ALTER TABLE [TABLENAME] DROP COLUMN [TEMP_COLUMN];
    
--extract email domain from email
SELECT EMAIL, RIGHT([EMAIL], LEN([EMAIL])-CHARINDEX('@',[EMAIL])) AS EMAIL_DOMAIN
FROM [TABLENAME];

--partion by row id
SELECT EMAIL_DOMAIN, ROW_NUMBER() OVER (PARTITION BY [EMAIL_DOMAIN] ORDER BY [EMAIL_DOMAIN]) as ROWID
FROM [TABLENAME];

--2 table look up
UPDATE A
SET A.[COL] = B.[UPDATE_COL]
FROM [TABLE] AS A, [LOOKUP_TABLE] AS B
WHERE A.[COL] = B.[LOOKUP_COL];

--get table columns
SELECT CONCAT('[',COLUMN_NAME,']') as [COLUMN_NAMES]
FROM [DBNAME].information_schema.columns
WHERE table_name = 'TABLENAME';

--UNION DISTINCT
SELECT COUNT(DISTINCT EMAIL)
FROM (
	SELECT EMAIL FROM TEST1
	UNION SELECT EMAIL FROM TEST2
	UNION SELECT EMAIL FROM TEST3
) A;

--CTE
WITH EXAMPLE AS (
  SELECT DISTINCT EMAIL
  FROM TEST1
)
SELECT *
FROM EXAMPLE;

--MULTI JOIN
SELECT A.NAME, B.ADDRESS, C.EMAIL
FROM TABLE1 AS A
    LEFT JOIN TABLE2 AS B ON A.ID=B.ID
    LEFT JOIN TABLE3 AS C ON A.ID=C.ID
    --ETC...
;

--FILTER BASED ON N MATCHES
SELECT *
	,((CASE WHEN A.[CASINO GAMBLER]='Y' THEN 1 ELSE 0 END) --casino_gambler =Y
		+ (CASE WHEN A.[MUSIC ENTHUSIAST]='Y' THEN 1 ELSE 0 END) --music_enthusiast =Y
		+ (CASE WHEN A.[ANTIQUES ENTHUSIAST]='Y' THEN 1 ELSE 0 END) --antiques_enthusiast =Y
		+ (CASE WHEN A.[ART ENTHUSIAST]='Y' THEN 1 ELSE 0 END) --art_enthusiast =Y
		+ (CASE WHEN A.[FINE ARTS ENTHUSIAST]='Y' THEN 1 ELSE 0 END) --fine_arts_enthusiast =Y
		+ (CASE WHEN A.[ART BUYER]='Y' THEN 1 ELSE 0 END) --art_buyer =Y
		+ (CASE WHEN A.[CULTURAL ARTS ENTHUSIASTS]='Y' THEN 1 ELSE 0 END) --cultural_arts_enthusiasts =Y
		+ (CASE WHEN A.[BOOK BUYER]='Y' THEN 1 ELSE 0 END) --book_buyer =Y
	) AS AMOUNT
INTO COUNT072925133
FROM GPCONSUMER..GPCONSUMER AS A INNER JOIN GPEMAIL..GPEMAIL AS B ON A.MATCHKEY=B.MATCHKEY AND A.FIRST=B.FIRST
WHERE --MUST HAVE 4 + of these
	((CASE WHEN A.[CASINO GAMBLER]='Y' THEN 1 ELSE 0 END) --casino_gambler =Y
		+ (CASE WHEN A.[MUSIC ENTHUSIAST]='Y' THEN 1 ELSE 0 END) --music_enthusiast =Y
		+ (CASE WHEN A.[ANTIQUES ENTHUSIAST]='Y' THEN 1 ELSE 0 END) --antiques_enthusiast =Y
		+ (CASE WHEN A.[ART ENTHUSIAST]='Y' THEN 1 ELSE 0 END) --art_enthusiast =Y
		+ (CASE WHEN A.[FINE ARTS ENTHUSIAST]='Y' THEN 1 ELSE 0 END) --fine_arts_enthusiast =Y
		+ (CASE WHEN A.[ART BUYER]='Y' THEN 1 ELSE 0 END) --art_buyer =Y
		+ (CASE WHEN A.[CULTURAL ARTS ENTHUSIASTS]='Y' THEN 1 ELSE 0 END) --cultural_arts_enthusiasts =Y
		+ (CASE WHEN A.[BOOK BUYER]='Y' THEN 1 ELSE 0 END) --book_buyer =Y
	) >= 4
;

